[package]
name = "jupiter-dev-executor"
version = "0.1.0"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"

[dependencies]
frame-benchmarking = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-executor = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "master" }
jupiter-runtime = { path = "../../../runtime/jupiter-dev" }

[features]
wasmtime = [
    "sc-executor/wasmtime",
]
wasmi-errno = [
    "sc-executor/wasmi-errno",
]
