[package]
name = "jupiter-para-cli"
version = "0.1.0"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"
parking_lot = "0.10.0"
serde_json = "1.0"
hex-literal = "0.2.1"
codec = { package = 'parity-scale-codec', version = '1.0.0' }
ansi_term = "0.12.1"
serde = { version = "1.0.119", features = ["derive"] }

# Substrate dependencies
sc-authority-discovery = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sc-basic-authorship = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sc-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sc-network = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sc-consensus-aura = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sc-consensus = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sc-finality-grandpa = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sc-client-api = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sc-rpc = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sc-informant = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sc-chain-spec = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sc-telemetry = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

sp-core = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sp-inherents = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sp-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sp-consensus-aura = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sp-consensus = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sp-finality-grandpa = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sp-runtime = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sp-api = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sc-cli = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
sc-service = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
sc-executor = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
frame-benchmarking = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sp-session = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sp-blockchain = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sp-block-builder = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sp-offchain = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sp-timestamp = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
sc-tracing = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

#pallet-contracts = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}
pallet-contracts = { path = "../../../vendor/substrate/frame/contracts" }

jupiter-primitives = { path = "../../../primitives" }
jupiter-para-runtime = { path = "../../../runtime/jupiter-para" }
jupiter-rpc = { path = "../../../rpc" }

# Cumulus dependencies
cumulus-consensus = { git = "https://github.com/paritytech/cumulus", branch = "rococo-v1"}
cumulus-collator = { git = "https://github.com/paritytech/cumulus", branch = "rococo-v1"}
cumulus-network = { git = "https://github.com/paritytech/cumulus", branch = "rococo-v1"}
cumulus-primitives = { git = "https://github.com/paritytech/cumulus", branch = "rococo-v1"}
cumulus-service = { git = "https://github.com/paritytech/cumulus", branch = "rococo-v1"}

# Polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1"}
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1"}
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1"}
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1"}

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}

[features]
default = ["cli"]
cli = [
    "sc-cli",
    "sc-service",
    "sc-executor/wasmi-errno",
]
wasmtime = [
    "sc-cli/wasmtime",
    "sc-service/wasmtime",
    "sc-executor/wasmtime",
]
