[workspace]
members = [
    "bin/node",
    "bin/node/executor",
    "bin/node-dev",
    "bin/node-para",
    "runtime/jupiter",
    "runtime/jupiter-dev",
    "runtime/jupiter-para",
    "primitives",
    "primitives/io",
    "rpc",
]
exclude = ["vendor/substrate"]

[profile.release]
panic = "unwind"

